### PR TITLE
Fixed usfb2osis always clearing caller

### PR DESCRIPTION
**Pull request by PlasmaPower**
GCC 6 spotted this bug for me, the semicolon meant that the second if statement did not contain the clear call. @postiffm could you check that this produces the intended result? If that's not the case, then the if statement should simply be removed.

### CODE REVIEW

**Comment by PlasmaPower** [comment]
@postiffm Could you adjust GitHub's settings to disallow merge commits for pull requests and instead enable squashing? (See here: https://help.github.com/articles/configuring-pull-request-merge-squashing/)

If we want to merge larger PRs we'll do that from the command line.

**Comment by PlasmaPower** [comment]
To be clear, the logic was equivalent to this before:

```c++
if (caller == "+") {
  caller.clear();
}
caller.clear();
```

**Comment by postiffm** [comment]
Thanks Lee. Very good catch. I'm still on g++ 5.4.0 so didn't
      have the benefit of this warning.
    I have checked it over and committed it on the new branch, merged
      into master, and committed it there also. Do you want to delete
      the usfb2osis-fix-caller-clear branch?
    
    Whenever I run into if statements formatted without { }, I add
      them.
    
     if ((caller == "+") || (caller == "-")) {
           caller.clear();
       }
    
    
    On 7/19/2016 5:27 PM, Lee Bousfield
      wrote:
    
    
      GCC 6 spotted this bug for me, the semicolon meant that the
        second if statement did not contain the clear call. @postiffm could you check that this
        produces the intended result? If that's not the case, then the
        if statement should simply be removed.
      
      You can view, comment on, or merge this pull request online
        at:
        https://github.com/postiffm/bibledit-gtk/pull/2
      Commit Summary
      
        Fixed usfb2osis always clearing caller
      
      File Changes
      
         M src/usfm2osis.cpp
          (4) 
      
      Patch Links:
      
        https://github.com/postiffm/bibledit-gtk/pull/2.patch
        https://github.com/postiffm/bibledit-gtk/pull/2.diff
      
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it
          on GitHub, or mute
          the thread.

**Comment by postiffm** [comment]
I might have already messed this up by what I did?
    
    
    On 7/19/2016 5:32 PM, Lee Bousfield
      wrote:
    
    
      @postiffm Could you adjust GitHub's
        settings to disallow merge commits for pull requests and instead
        enable squashing? (See here: https://help.github.com/articles/configuring-pull-request-merge-squashing/)
      If we want to merge larger PRs we'll do that from the command
        line.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by PlasmaPower** [comment]
@postiffm Not a huge deal, but you now have another merge commit in master :). Change the setting for next time (and while you're at it, set master and gtk3 as protected branches).

**Comment by postiffm** [comment]
I think I am starting to see the "problem" with that. It doesn't
      bother me to see that, but I suppose after a while it probably
      gets tiresome...
    
    
    On 7/19/2016 8:46 PM, Lee Bousfield
      wrote:
    
    
      @postiffm Not a huge deal, but you
        now have another merge commit in master :). Change the setting
        for next time (and while you're at it, set master and gtk3 as
        protected branches).
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Pull request merged**
